language: python
sudo: false
dist: trusty
python:
  - '3.6.2'

branches:
  only:
  - develop
  - master

node_js: '8'

env:
  matrix:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

cache:
  yarn: true
  pip: true
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/.ssh
    - static
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_88beac095338_key -iv $encrypted_88beac095338_iv -in client-secret.json.enc -out client-secret.json -d
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; source /home/travis/google-cloud-sdk/path.bash.inc; fi
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud config set project newdium-1283
  - if [ ! -f "$HOME/.ssh/google_compute_engine" ]; then gcloud compute ssh pythonapp@rank-web-group-2547 --command "ls ~/" --zone us-central1-b; fi

install:
  - git fetch --unshallow
  - yarn
  - git status

script:
  - pip list --format=columns
  - pip list | grep -F setuptools-scm && echo setuptools-found || pip install setuptools-scm
  - python -m gce.travis_build

after_success:
  - python -m gce.travis_deploy || travis_terminate 1
